# -*- coding: utf-8 -*-
"""BFS_chess

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIMbH0xHw1kMAYv5a_009el8IT6xLavJ
"""

'''
BFS - Knight's Shortest Path in a Chessboard
Problem Statement:
Given an N x N chessboard and a knight piece starting at position (x1, y1), find the
minimum number of moves to reach (x2, y2). The knight moves in an "L" shape: two
squares in one direction and then one perpendicular.
Constraints:
• 5 ≤ N ≤ 500
• 0 ≤ x1, y1, x2, y2 < N
Hint: Use BFS with a queue storing (x, y, moves).
'''

from collections import deque

def bfs(n, s, m):
    kmove = [(2, 1), (2, -1), (-2, 1), (-2, -1), (-1, 2), (-1, -2), (1, 2), (1, -2)]

    queue = deque([(s[0], s[1], 0)])
    visited = set()
    visited.add((s[0], s[1]))

    while queue:
        x, y, move = queue.popleft()
        if (x, y) == (m[0], m[1]):
            return move
        for dx, dy in kmove:
            nx, ny = x + dx, y + dy
            if 0 <= nx < n and 0 <= ny < n and (nx, ny) not in visited:
                visited.add((nx, ny))
                queue.append((nx, ny, move + 1))

    return -1

n = 8
s = (0, 0)
m = (7, 7)
print(bfs(n, s, m))