# -*- coding: utf-8 -*-
"""DFS_word

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIMbH0xHw1kMAYv5a_009el8IT6xLavJ
"""

'''
Word Search II using DFS
Problem Statement:
Given an m x n board of letters and a list of words, find all words that can be formed
by tracing adjacent letters (horizontally or vertically). The same letter cell cannot be
used more than once in a word.
def insert_word(trie, word):
'''
    node = trie
    for char in word:
        node = node.setdefault(char, {})
    node['#'] = word

def dfs(board, trie, i, j, path, res):
    if is_out_of_bounds(i, j, board): return
    tmp = board[i][j]
    if tmp not in trie: return

    node = trie[tmp]
    if '#' in node:
        res.append(path + tmp)
        del node['#']

    board[i][j] = "#"
    for x, y in [[0, -1], [0, 1], [1, 0], [-1, 0]]:
        dfs(board, node, i + x, j + y, path + tmp, res)
    board[i][j] = tmp

def is_out_of_bounds(i, j, board):
    return i < 0 or i >= len(board) or j < 0 or j >= len(board[0])

def findWords(board, words):
    trie = {}
    for word in words:
        insert_word(trie, word)

    res = []
    for i in range(len(board)):
        for j in range(len(board[0])):
            dfs(board, trie, i, j, "", res)

    return res

board = [
    ["o", "a", "a", "n"], ["e", "t", "a", "e"],["i", "h", "k", "r"], ["i", "f", "l", "v"]
]
words = ["oath", "pea", "eat", "rain"]

print(findWords(board, words))