# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7d_qUZt6DWmc7Jr8_RBEpzebLLIenlH
"""

def manhattan_distance(x1, y1, x2, y2):
    return abs(x1 - x2) + abs(y1 - y2)

def search_path(maze, start_pos, end_pos):
    queue = [(start_pos, 0)]
    explored = set()
    directions = [(-1, 0), (1, 0), (0, -1), (0, 1)]
    while queue:
        queue.sort(key=lambda item: item[1])
        current_pos, _ = queue.pop(0)
        x, y = current_pos
        if (x, y) == end_pos:
            print("Exit found!")
            return True
        explored.add((x, y))
        for dx, dy in directions:
            new_x, new_y = x + dx, y + dy
            if 0 <= new_x < len(maze) and 0 <= new_y < len(maze[0]) and maze[new_x][new_y] != '#' and (new_x, new_y) not in explored:
                distance = manhattan_distance(new_x, new_y, end_pos[0], end_pos[1])
                print(f"Queueing: {(new_x, new_y)} with distance {distance}")
                queue.append(((new_x, new_y), distance))
    print("No exit found.")
    return False

maze = [
    ['S', '.', '.', '#', '.'],
    ['#', '#', '.', '#', '.'],
    ['.', '.', '.', '.', 'E']
]

start_pos = end_pos = None
for row_index, row in enumerate(maze):
    for col_index, cell in enumerate(row):
        if cell == 'S':
            start_pos = (row_index, col_index)
        elif cell == 'E':
            end_pos = (row_index, col_index)

if start_pos and end_pos:
    search_path(maze, start_pos, end_pos)
else:
    print("Missing 'S' or 'E' in the maze!")

"""C. Dungeon Escape"""