# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7d_qUZt6DWmc7Jr8_RBEpzebLLIenlH
"""

class Puzzle:
    def __init__(self, state, goal):
        self.state = state
        self.goal = goal
        self.size = len(state)

    def find_tile(self, tile):
        for i in range(self.size):
            for j in range(self.size):
                if self.state[i][j] == tile:
                    return (i, j)
        return None

    def manhattan_distance(self):
        distance = 0
        for i in range(self.size):
            for j in range(self.size):
                if self.state[i][j] != 0:
                    goal_pos = self.find_position(self.state[i][j], self.goal)
                    distance += abs(i - goal_pos[0]) + abs(j - goal_pos[1])
        return distance

    def find_position(self, tile, state):
        for i in range(self.size):
            for j in range(self.size):
                if state[i][j] == tile:
                    return (i, j)
        return None

    def get_neighbors(self):
        neighbors = []
        x, y = self.find_tile(0)
        moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

        for dx, dy in moves:
            nx, ny = x + dx, y + dy
            if 0 <= nx < self.size and 0 <= ny < self.size:
                new_state = [row[:] for row in self.state]
                new_state[x][y], new_state[nx][ny] = new_state[nx][ny], new_state[x][y]
                neighbors.append(new_state)
        return neighbors


def a_star_solver(start, goal):
    open_list = [(start, 0, 0)]
    visited = set()
    visited.add(tuple(tuple(row) for row in start))

    while open_list:
        open_list.sort(key=lambda x: x[2])
        current_state, g, _ = open_list.pop(0)

        if current_state == goal:
            print("Solved the puzzle in", g, "steps!")
            return True

        puzzle = Puzzle(current_state, goal)
        for neighbor in puzzle.get_neighbors():
            if tuple(tuple(row) for row in neighbor) not in visited:
                visited.add(tuple(tuple(row) for row in neighbor))
                h = Puzzle(neighbor, goal).manhattan_distance()
                open_list.append((neighbor, g + 1, g + 1 + h))

    print("No solution found.")
    return False


def get_user_input():
    print("Enter the start state of the puzzle row by row.")
    print("Use 0 for the empty tile.")
    print("numbers between 0 and 8.")
    start_state = []
    for i in range(3):
        row = input(f"Enter row {i + 1} (space-separated numbers): ").strip().split()
        start_state.append([int(num) for num in row])
    return start_state


goal_state = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
]

start_state = get_user_input()

a_star_solver(start_state, goal_state)

"""Puzzle Solver (Hard Configuration)"""