# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIY-8cbSYi08jIjoDRdWHSCYv_euXlRL
"""

import random

places = {
    0: [0, 0, 0, 100],
    1: [2, 3, 10, 50],
    2: [5, 5, 20, 60],
    3: [8, 8, 30, 70],
    4: [10, 10, 40, 80]
}

def dist(a, b):
    return ((a[0] - b[0])**2 + (a[1] - b[1])**2)**0.5

def cost(path):
    time = 0
    for i in range(len(path) - 1):
        a, b = places[path[i]], places[path[i + 1]]
        time += dist(a, b)
        if time < b[2]:
            time = b[2]
        if time > b[3]:
            return float('inf')
    return time

def swap(path):
    x, y = random.sample(range(1, len(path) - 1), 2)
    path[x], path[y] = path[y], path[x]

def mix(p1, p2):
    cut = random.randint(1, len(p1) - 2)
    child = p1[:cut] + [p for p in p2 if p not in p1[:cut]]
    return child

def solve(size, tries):
    pop = [random.sample(list(places.keys())[1:], len(places) - 1) for _ in range(size)]
    for p in pop:
        p.insert(0, 0)
        if p[-1] != 4:
            p[-1] = 4

    for _ in range(tries):
        pop.sort(key=lambda p: cost(p))
        next_pop = pop[:size // 2]
        for i in range(len(next_pop) - 1):
            child = mix(next_pop[i], next_pop[i + 1])
            if random.random() < 0.2:
                swap(child)
            child.insert(0, 0)
            if child[-1] != 4:
                child[-1] = 4
            next_pop.append(child)
        pop = next_pop

    best = pop[0]
    return best, cost(best)

def show(path):
    time = 0
    for i in range(len(path) - 1):
        a, b = path[i], path[i + 1]
        d = dist(places[a], places[b])
        time += d
        if time < places[b][2]:
            time = places[b][2]
        print(f"{a} → {b} | Time: {round(time, 2)}")
    print("Total Time:", round(time, 2))

best, total = solve(size=10, tries=50)
print("Best Path:", best)
print("Total:", total)
show(best)

"""1. Travelling Salesman Problem (TSP) with Time Windows
o Optimize a route visiting cities only within specific time ranges.
o Combines path optimization with scheduling constraints.
"""