# -*- coding: utf-8 -*-
"""UCS_EffortPath

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KIMbH0xHw1kMAYv5a_009el8IT6xLavJ
"""

'''
Minimum Effort Path
Problem Statement:
You are given a m x n grid where heights[i][j] represents the height of a cell. You can
move up, down, left, or right, but the effort required is the absolute difference in
height between the current cell and the next cell. Find the minimum effort needed to
travel from the top-left corner to the bottom-right corner
'''

import heapq

def minimumEffortPath(heights):
    m, n = len(heights), len(heights[0])
    directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]
    pq = [(0, 0, 0)]
    effort = [[float('inf')] * n for _ in range(m)]
    effort[0][0] = 0

    while pq:
        max_effort, x, y = heapq.heappop(pq)

        if x == m - 1 and y == n - 1:
            return max_effort

        for dx, dy in directions:
            nx, ny = x + dx, y + dy
            if 0 <= nx < m and 0 <= ny < n:
                new_effort = max(max_effort, abs(heights[x][y] - heights[nx][ny]))

                if new_effort < effort[nx][ny]:
                    effort[nx][ny] = new_effort
                    heapq.heappush(pq, (new_effort, nx, ny))

    return -1
heights = [
    [1, 2, 2],
    [3, 8, 2],
    [5, 3, 5]
]

print(minimumEffortPath(heights))