# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EIY-8cbSYi08jIjoDRdWHSCYv_euXlRL
"""

def calculate_distance(loc1, loc2):
    return ((loc1[0] - loc2[0])**2 + (loc1[1] - loc2[1])**2)**0.5

def solve_vrp(locations, demands, vehicle_capacity):
    vehicles = []
    depot = locations[0]
    remaining_demands = {i: demands[i] for i in range(1, len(locations))}

    while remaining_demands:
        vehicle_route = [0]
        vehicle_load = 0
        current_location = depot

        while True:
            next_location = None
            shortest_distance = float('inf')

            for loc, demand in remaining_demands.items():
                if vehicle_load + demand <= vehicle_capacity:
                    dist = calculate_distance(current_location, locations[loc])
                    if dist < shortest_distance:
                        next_location = loc
                        shortest_distance = dist

            if next_location is None:
                break

            vehicle_route.append(next_location)
            vehicle_load += remaining_demands[next_location]
            current_location = locations[next_location]
            del remaining_demands[next_location]

        vehicle_route.append(0)
        vehicles.append(vehicle_route)

    return vehicles

locations = [
    (0, 0),
    (2, 3),
    (5, 5),
    (8, 8),
    (1, 7)
]

demands = [0, 2, 4, 6, 3]
vehicle_capacity = 10

routes = solve_vrp(locations, demands, vehicle_capacity)

for i, route in enumerate(routes):
    readable_route = " → ".join([f"[{idx} → {locations[idx]}]" for idx in route])
    print(f"Vehicle {i + 1}: Route: {readable_route}")

"""2. Vehicle Routing Problem with Capacity Constraints (VRP)
o Deliver goods to multiple locations using a limited fleet.
o Add constraints like fuel, cargo weight, or delivery priority.
"""